FROM python:3.6-buster


RUN apt-get update && \
    apt-get install -y \
    zip \
    unzip \
    tcpdump \
    bridge-utils \
    net-tools \
    iptables \
    tcpdump \
    libpcap-dev && apt-get clean

RUN apt-get -qq -y install \
    python-dev \
    libnetfilter-queue-dev \
    build-essential

RUN apt-get -qq -y install \
    python3-pip \
    vim \
    tmux \
    fping \
    iperf \
    build-essential

WORKDIR app
COPY . .
RUN ls
RUN gcc bridge.c -o bridge





